[project]
name = "fraud-prevention-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "catboost>=1.2.8",
    "mage-ai[streaming]>=0.9.78",
]
